# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

repository: jtferson/jtferson.github.io

title: GameDev Tales
#subtitle: "Version 4.0"
email: jtferson@gmail.com

#logo: "/assets/images/bio-photo.jpg"
#masthead_title: "My Custom Title"

author:
  name     : "Red J"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "C#/C++ programmer"
  location : "Moscow, Russia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jtferson"



description: >- # this means to ignore newlines until "baseurl:"
  # GameDev Tales
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jtferson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  jtferson

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "dark" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      #classes: wide
      author_profile: true
      read_time: true
      show_date: true
      share: true
        
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-analytics
  

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jtferson"
      
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-6Z0DTP462C          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking


 


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
